FrontendBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.FrontendBucket.name}
    WebsiteConfiguration:
      IndexDocument: index.html
      ErrorDocument: index.html
    PublicAccessBlockConfiguration:
      BlockPublicAcls: false
      BlockPublicPolicy: false
      IgnorePublicAcls: false
      RestrictPublicBuckets: false

FrontendBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref FrontendBucket
    PolicyDocument:
      Statement:
        - Sid: PublicReadGetObject
          Effect: Allow
          Principal: '*'
          Action:
            - s3:GetObject
          Resource: arn:aws:s3:::${self:custom.FrontendBucket.name}/*
