FROM alpine:3.20
RUN apk add --no-cache bash curl jq nodejs npm python3 py3-pip \
 && pip install --no-cache-dir awscli
WORKDIR /app
COPY scripts /app/scripts
ENV AWS_ACCESS_KEY_ID=test \
    AWS_SECRET_ACCESS_KEY=test \
    AWS_DEFAULT_REGION=us-east-1 \
    AWS_PAGER=""
ENTRYPOINT ["/bin/bash"]
