service: auction-service

plugins:
  - serverless-esbuild
  - serverless-pseudo-parameters
  - serverless-offline
  - serverless-localstack

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    AWS_REGION: ${self:provider.region}
    # When running locally:
    AWS_ENDPOINT: ${self:custom.config.awsEndpoint}
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID, 'test'}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY, 'test'}
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
    MAIL_QUEUE_URL: ${self:custom.config.mailQueueUrl}
    AUCTIONS_BUCKET_NAME: ${self:custom.config.auctionsBucketName}
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}
    - ${file(iam/MailQueueIAM.yml):MailQueueIAM}
    - ${file(iam/AuctionsBucketIAM.yml):AuctionsBucketIAM}

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}
    AuctionsBucket: ${file(resources/AuctionsBucket.yml):AuctionsBucket}
    AuctionsBucketPolicy: ${file(resources/AuctionsBucket.yml):AuctionsBucketPolicy}
    FrontendBucket: ${file(resources/FrontendBucket.yml):FrontendBucket}
    FrontendBucketPolicy: ${file(resources/FrontendBucket.yml):FrontendBucketPolicy}
  Outputs:
    FrontendBucketName:
      Value: !Ref FrontendBucket
    FrontendUrl:
      Value: !GetAtt FrontendBucket.WebsiteURL
    
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
          cors: true
          authorizer: ${self:custom.config.authorizer}

  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          method: GET
          path: /auctions
          cors: true
          authorizer: ${self:custom.config.authorizer}

  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - http:
          method: GET
          path: /auction/{id}
          cors: true
          authorizer: ${self:custom.config.authorizer}

  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http:
          method: PATCH
          path: auction/{id}/bid
          cors: true
          authorizer: ${self:custom.config.authorizer}

  uploadAuctionPicture:
    handler: src/handlers/uploadAuctionPicture.handler
    events:
      - http:
          method: PATCH
          path: auction/{id}/picture
          cors: true
          authorizer: ${self:custom.config.authorizer}

  processAuctions:
    handler: src/handlers/processAuctions.handler
    events:
      - schedule: rate(1 minute)

custom:
  serverless-offline:
    noPrependStageInUrl: true
  config: ${file(config/config.${self:provider.stage}.yml)}
  localstack:
    stages: [local]
    host: http://localhost
    edgePort: 4566
    autostart: false
    lambda:
      mountCode: false
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: "node20"
    platform: "node"
    external:
      - aws-sdk
  AuctionsTable:
    name: AuctionsTable-${self:provider.stage}
    arn: !GetAtt AuctionsTable.Arn
  MailQueue:
    arn: ${self:custom.config.mailQueueArn}
    url: ${self:custom.config.mailQueueUrl}
  AuctionsBucket:
    name: ${self:custom.config.auctionsBucketName}
  FrontendBucket:
    name: ${self:custom.config.frontendBucketName}
