service: auction-service

plugins:
  - serverless-esbuild
  - serverless-pseudo-parameters
  - serverless-offline
  - serverless-localstack

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    AWS_REGION: ${self:provider.region}
    # When running locally:
    AWS_ENDPOINT: ${self:custom.awsEndpoint.${self:provider.stage}, ''}
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID, 'test'}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY, 'test'}
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
    MAIL_QUEUE_URL: ${self:custom.MailQueue.url.${self:provider.stage}, ''}
    AUCTIONS_BUCKET_NAME: ${self:custom.AuctionsBucket.name}
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}
    - ${file(iam/MailQueueIAM.yml):MailQueueIAM}
    - ${file(iam/AuctionsBucketIAM.yml):AuctionsBucketIAM}

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}
    AuctionsBucket: ${file(resources/AuctionsBucket.yml):AuctionsBucket}
    AuctionsBucketPolicy: ${file(resources/AuctionsBucket.yml):AuctionsBucketPolicy}
    
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
          cors: true
          authorizer: ${self:custom.authorizer.${self:provider.stage}}

  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          method: GET
          path: /auctions
          cors: true
          authorizer: ${self:custom.authorizer.${self:provider.stage}}

  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - http:
          method: GET
          path: /auction/{id}
          cors: true
          authorizer: ${self:custom.authorizer.${self:provider.stage}}

  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http:
          method: PATCH
          path: auction/{id}/bid
          cors: true
          authorizer: ${self:custom.authorizer.${self:provider.stage}}

  uploadAuctionPicture:
    handler: src/handlers/uploadAuctionPicture.handler
    events:
      - http:
          method: PATCH
          path: auction/{id}/picture
          cors: true
          authorizer: ${self:custom.authorizer.${self:provider.stage}}

  processAuctions:
    handler: src/handlers/processAuctions.handler
    events:
      - schedule: rate(1 minute)

custom:
  awsEndpoint:
    local: http://localhost:4566
    dev: ''
    prod: ''
  localstack:
    stages: [local]
    lambda:
      mountCode: true
  authorizer:
    local: ''
    dev: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:auth-service-${self:provider.stage}-auth
    prod: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:auth-service-${self:provider.stage}-auth
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: "node20"
    platform: "node"
    external:
      - aws-sdk
  AuctionsTable:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn
  MailQueue:
    arn: ${cf:notification-service-${self:provider.stage}.MailQueueArn, ''}
    url:
      local: http://localhost:4566/000000000000/MailQueue-local
      dev: ${cf:notification-service-${self:provider.stage}.MailQueueUrl, ''}
      prod: ${cf:notification-service-${self:provider.stage}.MailQueueUrl, ''}
  AuctionsBucket:
    name: ${self:custom.AuctionsBucket.${self:provider.stage}, self:custom.AuctionsBucket.default}
    default: auctions-bucket-sj19asxm-${self:provider.stage}
    local: auctions-bucket-sj19asxm-local
