
service:
  name: serverless-auth0-authorizer

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  environment:
    JWKS_URI: https://<YOUR_AUTH0_DOMAIN>/.well-known/jwks.json # Placeholder - User needs to configure
    AUTH0_AUDIENCE: https://<YOUR_API_IDENTIFIER> # Placeholder - User needs to configure
    AUTH0_ISSUER: https://<YOUR_AUTH0_DOMAIN>/ # Placeholder - User needs to configure

functions:
  auth:
    handler: src/handlers/auth.handler
    cors: true
  publicEndpoint:
    handler: src/handlers/public.handler
    events:
      - http:
          path: public
          method: POST
          cors: true
  privateEndpoint:
    handler: src/handlers/private.handler
    events:
      - http:
          path: private
          method: POST
          authorizer: auth
          cors: true

resources:
  Resources:
    # This response is needed for custom authorizer failures cors support ¯\_(ツ)_/¯
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    AuthFailureGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
custom:
  bundle:
    linting: false
